name: user_repository
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  key_value_storage:
    path: ../key_value_storage


dev_dependencies:

