name: MyDictionary
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dictionary_provider:
    path: packages/dictionary_provider
  domain_models:
    path: packages/domain_models
  db_service:
    path: packages/db_service
  key_value_storage:
    path: packages/key_value_storage
  google_api_service:
    path: packages/google_api_service
  user_repository:
    path: packages/user_repository
  main_screen:
    path: packages/features/main_screen
  translation_screen:
    path: packages/features/translation_screen
  wizz_decks_screen:
    path: packages/features/wizz_decks_screen
  wizz_cards_screen:
    path: packages/features/wizz_cards_screen
  wizz_training_module:
    path: packages/wizz_training_module
  simple_translation_card:
    path: packages/features/simple_translation_card
  dictionaries_screen:
    path: packages/features/dictionaries_screen
  search_word_screen:
    path: packages/features/search_word_screen
  flashcards_screen:
    path: packages/features/flashcards_screen
  go_router: ^6.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/icons/
   - assets/pictures/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSansCondensed
      fonts:
        - asset: assets/fonts/OpenSansCondensed-Light.ttf
        - asset: assets/fonts/OpenSansCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSansCondensed-LightItalic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
