name: key_value_storage
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  hive: ^2.0.4
  path_provider: ^2.0.2
  path: ^1.8.2

dev_dependencies:
  build_runner: ^2.0.5
  hive_generator: any
  flutter_lints: ^2.0.0

